name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t debisho/number-api .
        docker push debisho/number-api

    - name: SSH into EC2 and Deploy
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.EC2_HOST }} $(ssh-keyscan -H ${{ secrets.EC2_HOST }}) 2> /dev/null" >> ~/.ssh/known_hosts"
        ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }}
        docker pull debisho/number-api
        docker stop number-api || true
        docker rm number-api || true
        docker run -d -p 80:8000 --name number-api debisho/number-api

